/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_dxzq_multifactor_optimizer_IpOptimizer */

#ifndef _Included_net_dxzq_multifactor_optimizer_IpOptimizer
#define _Included_net_dxzq_multifactor_optimizer_IpOptimizer
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     net_dxzq_multifactor_optimizer_IpOptimizer
	* Method:    createQPandCalc
	* Signature: (I[[D[D[D[DLjava/util/List;Ljava/util/List;I[D)Z
	*/
	JNIEXPORT jboolean JNICALL Java_net_dxzq_multifactor_optimizer_IpOptimizer_createQPandCalc
		(JNIEnv *, jobject, jint, jobjectArray, jdoubleArray, jdoubleArray, jdoubleArray, jobject, jobject, jint, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
